# Generated by Django 6.0.4 on 2026-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_rename_meld_gamelog_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='delete_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='host_change_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
