# Generated by Django 6.0.4 on 2026-05-12 07:55

from django.db import migrations

def create_bot(apps, schema_editor):
    User = apps.get_model("api", "User")

    if not User.objects.filter(username="BOT").exists():
        User.objects.create(
            username="BOT0",
            email="bot0@bot.com",
            is_bot=True,
            is_online=False,
            avatar="avatars/bot.jpg",
        )
    if not User.objects.filter(username="BOT").exists():
        User.objects.create(
            username="BOT1",
            email="bot1@bot.com",
            is_bot=True,
            is_online=False,
            avatar="avatars/bot.jpg",
        )
    if not User.objects.filter(username="BOT").exists():
        User.objects.create(
            username="BOT2",
            email="bot2@bot.com",
            is_bot=True,
            is_online=False,
            avatar="avatars/bot.jpg",
        )
    if not User.objects.filter(username="BOT").exists():
        User.objects.create(
            username="BOT3",
            email="bot3@bot.com",
            is_bot=True,
            is_online=False,
            avatar="avatars/bot.jpg",
        )
    if not User.objects.filter(username="BOT").exists():
        User.objects.create(
            username="BOT4",
            email="bot4@bot.com",
            is_bot=True,
            is_online=False,
            avatar="avatars/bot.jpg",
        )
    if not User.objects.filter(username="BOT").exists():
        User.objects.create(
            username="BOT5",
            email="bot5@bot.com",
            is_bot=True,
            is_online=False,
            avatar="avatars/bot.jpg",
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_is_bot'),
    ]

    operations = [
        migrations.RunPython(create_bot),
    ]
    

