# Generated by Django 6.0.4 on 2026-05-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_friendship_blocked_at_friendship_blocked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
