# Generated by Django 6.0.4 on 2026-07-08 14:29

from django.db import migrations

def create_achievements(apps, schema_editor):
    Achievement = apps.get_model("api", "Achievement")
    
    if not Achievement.objects.filter(code="LUCKY").exists():
        Achievement.objects.create(
            code="LUCKY",
            title="lucky",
            description="tu as trouvé un trèfle à quatre feuilles en arrivant",
            condition="",
            icon="icons/clover.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="SUPER_LUCKY").exists():
        Achievement.objects.create(
            code="SUPER_LUCKY",
            title="super lucky",
            description="tu as trouvé 3 trèfles à quatre feuilles en arrivant",
            condition="",
            icon="icons/triple_clover.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="LOSER_1").exists():
        Achievement.objects.create(
            code="LOSER_1",
            title="loser 1",
            description="atteindre -10 elo",
            condition="",
            icon="icons/loser_1.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="LOSER_2").exists():
        Achievement.objects.create(
            code="LOSER_2",
            title="loser 2",
            description="atteindre -42 elo",
            condition="",
            icon="icons/loser_2.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="LOSER_3").exists():
        Achievement.objects.create(
            code="LOSER_3",
            title="loser 3",
            description="atteindre -67 elo",
            condition="",
            icon="icons/loser_3.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="LOSER_4").exists():
        Achievement.objects.create(
            code="LOSER_4",
            title="loser 4",
            description="atteindre -69 elo",
            condition="",
            icon="icons/loser_4.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="LOSER_5").exists():
        Achievement.objects.create(
            code="LOSER_5",
            title="loser 5",
            description="atteindre -420 elo",
            condition="",
            icon="icons/loser_5.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="WINNER_1").exists():
        Achievement.objects.create(
            code="WINNER_1",
            title="winner 1",
            description="atteindre 10 elo",
            condition="",
            icon="icons/winner_1.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="WINNER_2").exists():
        Achievement.objects.create(
            code="WINNER_2",
            title="winner 2",
            description="atteindre 42 elo",
            condition="",
            icon="icons/winner_2.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="WINNER_3").exists():
        Achievement.objects.create(
            code="WINNER_3",
            title="winner 3",
            description="atteindre 67 elo",
            condition="",
            icon="icons/winner_3.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="WINNER_4").exists():
        Achievement.objects.create(
            code="WINNER_4",
            title="winner 4",
            description="atteindre 69 elo",
            condition="",
            icon="icons/winner_4.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="WINNER_5").exists():
        Achievement.objects.create(
            code="WINNER_5",
            title="winner 5",
            description="atteindre 420 elo",
            condition="",
            icon="icons/winner_5.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="WINNER").exists():
        Achievement.objects.create(
            code="WINNER",
            title="winner",
            description="gagne une partie",
            condition="",
            icon="icons/winner.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="LOSER").exists():
        Achievement.objects.create(
            code="LOSER",
            title="loser",
            description="perdre une partie",
            condition="",
            icon="icons/loser.jpg",
            is_hidden=False
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(create_achievements),
    ]
    

